apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - kibishiiAzureStorageClass.yaml
patches:
  - path: worker-image-patch.yaml
  - path: jump-pad-image-patch.yaml
  - path: etcd-image-patch.yaml