apiVersion: v1
kind: Pod
metadata:
  name: jump-pad
spec:
  containers:
  - name: jump-pad
    image: harbor-repo.vmware.com/harbor-ci/dpcpinternal/jump-pad:fix-log4j-cves-104e5a6-15.Feb.2022.06.08.20
